name: Generate UML Diagrams for Swift

on:
  push:
    branches:
      - main  # Выполнять workflow при пуше в ветку main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y plantuml swift
        mkdir -p diagrams

    - name: Generate UML Diagrams
      run: |
        # Используем PlantUML для обработки файлов Swift
        find ./test_app -name "*.swift" | xargs plantuml -o diagrams

    - name: Upload UML diagrams
      uses: actions/upload-artifact@v3
      with:
        name: UML-Diagrams
        path: diagrams
