name: Run Swift Playgrounds

on:
  push:
    branches:
      - main  # Запускать при пуше в ветку main

jobs:
  run-playgrounds:
    runs-on: macos-latest  # Используется macOS, так как требуется для Xcode

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Swift Playgrounds
      uses: thisIsTheFoxe/swift-playgrounds-action@v1
      with:
        project-path: test-app/test-app.xcodeproj  # Укажите путь к вашему .xcodeproj
